TelephoneDirectory/Controllers/AdminUIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using PagedList.Mvc;
using TelephoneDirectory.Models.Entity;

namespace TelephoneDirectory.Controllers
{
    public class AdminUIController : Controller
    {
        InternShipProjectEntitiesOne InternShipProjectEntities = new InternShipProjectEntitiesOne();
        public ActionResult Index(int sayfa = 1)
        {
            var result = InternShipProjectEntities.Working.ToList().ToPagedList(sayfa, 5);
            return View(result);
        }

        [HttpGet]
        public ActionResult Login()
        {                      
            return View();
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            var result = InternShipProjectEntities.Admin.Where(i => i.UserName == admin.UserName && i.Password == admin.Password);            
            if (result != null && result.Count() > 0)
            {
                Session["UserName"] = result;
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Kullanıcı adı veya şifre yanlış.";
            }
            return View();
        }

        [HttpGet]
        public ActionResult AddNewWorking()
        {
            List<SelectListItem> Values1 = (from i in InternShipProjectEntities.Department.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.DepartmentName,
                                                Value = i.DepartmentId.ToString(),
                                            }).ToList();
            ViewBag.Value1 = Values1;
            List<SelectListItem> Values2 = (from i in InternShipProjectEntities.Administrator.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.AdministratorName,
                                                Value = i.AdministratorId.ToString(),
                                            }).ToList();
            ViewBag.Value2 = Values2;
            return View();
        }

        [HttpPost]
        public ActionResult AddNewWorking(Working NewWorking)
        {
            if (NewWorking.Name != null && NewWorking.Surname != null && NewWorking.TelephoneNumber != null)
            {
                var NewWorkingDepartmentID = InternShipProjectEntities.Department.Where(i => i.DepartmentId == NewWorking.Department).FirstOrDefault();
                var NewWorkingAdministratorId = InternShipProjectEntities.Administrator.Where(i => i.AdministratorId == NewWorking.Administrator).FirstOrDefault();
                NewWorking.Department = NewWorkingDepartmentID.DepartmentId;
                NewWorking.Administrator = NewWorkingAdministratorId.AdministratorId;
                InternShipProjectEntities.Working.Add(NewWorking);
                InternShipProjectEntities.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DepartmentInformation()
        {
            var result = InternShipProjectEntities.Department.ToList();
            return View(result);
        }

        [HttpPost]
        public ActionResult DepartmentInformation(Department department)
        {
            var result = InternShipProjectEntities.Department.Where(i => i.DepartmentName == department.DepartmentName);
            if (!(result.Count() > 0))
            {
                if (department.DepartmentName != null)
                {
                    InternShipProjectEntities.Department.Add(department);
                    InternShipProjectEntities.SaveChanges();
                }
            }
            return RedirectToAction("DepartmentInformation");
        }

        public ActionResult DeleteDepartment(int Id)
        {
            var result = InternShipProjectEntities.Department.Find(Id);
            var Control = InternShipProjectEntities.Working.Where(i => i.Department1.DepartmentName == result.DepartmentName);
            if (!(Control.Count() > 0))
            {
                InternShipProjectEntities.Department.Remove(result);
                InternShipProjectEntities.SaveChanges();
            }
            else
            {
                ViewBag.Message = "Bu departmanda çalışan personeller bulunmaktadır.";
            }
            return RedirectToAction("DepartmentInformation");
        }

        public ActionResult UpdateDepartment(int Id)
        {
            var result = InternShipProjectEntities.Department.Find(Id);
            return View(result);
        }

        public ActionResult UpdateDataDepartment(Department department)
        {
            var result = InternShipProjectEntities.Department.Find(department.DepartmentId);
            result.DepartmentName = department.DepartmentName;
            InternShipProjectEntities.SaveChanges();
            return RedirectToAction("DepartmentInformation");
        }

        public ActionResult Delete(int Id)
        {
            var Working = InternShipProjectEntities.Working.Find(Id);
            InternShipProjectEntities.Working.Remove(Working);
            InternShipProjectEntities.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Update(int Id)
        {
            var result = InternShipProjectEntities.Working.Find(Id);
            return View(result);
        }

        public ActionResult UpdateData(Working working)
        {
            var value = InternShipProjectEntities.Working.Find(working.WorkingId);
            value.Name = working.Name;
            value.Surname = working.Surname;
            value.TelephoneNumber = working.TelephoneNumber;
            value.Department1.DepartmentName = working.Department1.DepartmentName;
            InternShipProjectEntities.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AdminOperation()
        {
            var result = InternShipProjectEntities.Admin.ToList();
            return View(result);
        }

        [HttpPost]
        public ActionResult AdminOperation(Admin admin)
        {
            var result = InternShipProjectEntities.Admin.Where(i => i.UserName == admin.UserName);
            if (admin.UserName != null && admin.Password != null)
            {
                if (!(result.Count() > 0))
                {
                    InternShipProjectEntities.Admin.Add(admin);
                    InternShipProjectEntities.SaveChanges();
                }
            }
            return RedirectToAction("AdminOperation");
        }

        public ActionResult AdminDelete(int Id)
        {
            var admin = InternShipProjectEntities.Admin.Find(Id);
            if (admin != null)
            {
                InternShipProjectEntities.Admin.Remove(admin);
                InternShipProjectEntities.SaveChanges();
            }
            return RedirectToAction("AdminOperation");
        }       

        public ActionResult AdminUpdate(int Id)
        {
            var result = InternShipProjectEntities.Admin.Find(Id);
            return View(result);
        }

        public ActionResult AdminDataUpdate(Admin admin)
        {
            var value = InternShipProjectEntities.Admin.Find(admin.AdminId);
            value.UserName = admin.UserName;
            value.Password = admin.Password;
            InternShipProjectEntities.SaveChanges();
            return RedirectToAction("AdminOperation");
        }

        [HttpGet]
        public ActionResult AdministratorOperation()
        {
            var result = InternShipProjectEntities.Administrator.ToList();
            return View(result);
        }

        [HttpPost]
        public ActionResult AdministratorOperation(Administrator administrator)
        {
            var result = InternShipProjectEntities.Administrator.Where(i => i.AdministratorName == administrator.AdministratorName);
            if (!(result.Count() > 0))
            {
                InternShipProjectEntities.Administrator.Add(administrator);
                InternShipProjectEntities.SaveChanges();
            }
            return RedirectToAction("AdministratorOperation");
        }

        public ActionResult AdministratorDelete(int Id)
        {
            var administrator = InternShipProjectEntities.Administrator.Find(Id);
            var control = InternShipProjectEntities.Working.Where(i => i.Administrator1.AdministratorName == administrator.AdministratorName);
            if (!(control.Count()>0))
            {
                if (administrator != null)
                {
                    InternShipProjectEntities.Administrator.Remove(administrator);
                    InternShipProjectEntities.SaveChanges();
                }
            }
            else
            {
                ViewBag.Message = "Bu yönetici altında çalışanlar mevcut silme işlemi başarısız";
            }
            return RedirectToAction("AdministratorOperation");
        }

        public ActionResult AdministratorUpdate(int Id)
        {
            var result = InternShipProjectEntities.Administrator.Find(Id);
            return View(result);
        }

        public ActionResult AdministratorDataUpdate(Administrator administrator)
        {
            var value = InternShipProjectEntities.Administrator.Find(administrator.AdministratorId);
            if (value!=null)
            {
                value.AdministratorName = administrator.AdministratorName;
                InternShipProjectEntities.SaveChanges();
            }            
            return RedirectToAction("AdministratorOperation");
        }

        public ActionResult LogOut()
        {

TelephoneDirectory/Views/AdminUI/AddNewWorking.cshtml
@model TelephoneDirectory.Models.Entity.Working

@{
    ViewBag.Title = "AddNewWorking";
}
@if (Session["UserName"]!=null)
{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Yeni Kullanıcı Ekle</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand">Yeni Kullanıcı Ekle</a>
                </div>
            </div>
        </nav>
        <div>
            <form method="post">
                <div class="form-group">
                    <label>Ad</label>
                    <input type="text" class="form-control" name="Name" maxlength="10" required />
                </div>
                <div class="form-group">
                    <label>Soyad</label>
                    <input type="text" class="form-control" name="Surname" maxlength="10" required />
                </div>
                <div class="form-group">
                    <label>Telefon</label>
                    <input type="tel" class="form-control" name="TelephoneNumber" maxlength="11" required />
                </div>
                <div class="form-group">
                    <label>Departman</label>
                    @Html.DropDownListFor(i => i.Department, (List<SelectListItem>)ViewBag.Value1, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Yönetici</label>
                    @Html.DropDownListFor(i => i.Administrator, (List<SelectListItem>)ViewBag.Value2, new { @class = "form-control" })
                </div>
                <div style="margin-top:15px">
                    <button class="btn btn-info" href="/AdminUI/Index">Ekle</button>
                </div>
            </form>
        </div>
    </body>
</html>
}
else
{
<a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}

TelephoneDirectory/Views/AdminUI/AdminOperation.cshtml
@using TelephoneDirectory.Models.Entity
@model List<Admin>
@{
    ViewBag.Title = "PasswordOperation";
}
@if (Session["UserName"] != null)
{
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Admin İşlemleri</a>
            </div>
        </div>
    </nav>
    <table class="table table-bordered">
        <tr>
            <th>AdminId</th>
            <th>Kullanıcı Adı</th>
            <th>Şifre</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
        <tbody>
            @foreach (var information in Model)
            {
                <tr>
                    <td>@information.AdminId</td>
                    <td>@information.UserName</td>
                    <td>@information.Password</td>
                    <td><a class="btn btn-danger" href="/AdminUI/AdminDelete/@information.AdminId">Sil</a></td>
                    <td><a class="btn btn-success" href="/AdminUI/AdminUpdate/@information.AdminId">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        <form method="post">
            <div class="form-group">
                <label>Kullanıcı Adı</label>
                <input type="text" class="form-control" name="UserName" required />
            </div>
            <div class="form-group">
                <label>Şifre</label>
                <input type="text" class="form-control" name="Password" required />
            </div>
            <div style="margin-top:15px">
                <button class="btn btn-info" href="/AdminUI/AdminOperation">Admin Ekle</button>
            </div>
        </form>
    </div>
}
else
{
    <a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}

TelephoneDirectory/Views/AdminUI/AdminUpdate.cshtml
@model TelephoneDirectory.Models.Entity.Admin
@{
    ViewBag.Title = "AdminUpdate";
}
@if (Session["UserName"] != null)
{
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Admin Bilgileri Güncelle</a>
            </div>
        </div>
    </nav>
    using (Html.BeginForm("AdminDataUpdate", "AdminUI", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.AdminId)
            @Html.TextBoxFor(m => m.AdminId, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.UserName)
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
            <br />
        </div>
        <div>
            <button class="btn btn-info">Güncelle</button>
        </div>
    }
}
else
{
    <a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}

TelephoneDirectory/Views/AdminUI/AdministratorOperation.cshtml
@using TelephoneDirectory.Models.Entity
@model List<Administrator>
@{
    ViewBag.Title = "AdministratorOperation";
}

@if (Session["UserName"] != null)
{
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Admin İşlemleri</a>
            </div>
        </div>
    </nav>
    <table class="table table-bordered">
        <tr>
            <th>Yönetici Id</th>
            <th>Yönetici Adı</th>            
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
        <tbody>
            @foreach (var information in Model)
            {
                <tr>
                    <td>@information.AdministratorId</td>                    
                    <td>@information.AdministratorName</td>                    
                    <td><a class="btn btn-danger" href="/AdminUI/AdministratorDelete/@information.AdministratorId">Sil</a></td>
                    <td><a class="btn btn-success" href="/AdminUI/AdministratorUpdate/@information.AdministratorId">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        <form method="post">
            <div class="form-group">
                <label>Yönetici Adı Soyadı</label>
                <input type="text" class="form-control" name="AdministratorName" required />
            </div>            
            <div style="margin-top:15px">
                <button class="btn btn-info" href="/AdminUI/AdministratorOperation">Yönetici Ekle</button>
            </div>
        </form>
    </div>
}
else
{
    <a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}

TelephoneDirectory/Views/AdminUI/AdministratorUpdate.cshtml
@model TelephoneDirectory.Models.Entity.Administrator
@{
    ViewBag.Title = "AdministratorUpdate";
}
@if (Session["UserName"] != null)
{
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Admin Bilgileri Güncelle</a>
            </div>
        </div>
    </nav>
    using (Html.BeginForm("AdministratorDataUpdate", "AdminUI", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.AdministratorId)
            @Html.TextBoxFor(m => m.AdministratorId, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.AdministratorName)
            @Html.TextBoxFor(m => m.AdministratorName, new { @class = "form-control" })            
            <br />
        </div>
        <div>
            <button class="btn btn-info">Güncelle</button>
        </div>
    }

}
else
{
    <a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}

TelephoneDirectory/Views/AdminUI/DepartmentInformation.cshtml
@using TelephoneDirectory.Models.Entity
@model List<Department>
@{
    ViewBag.Title = "DepartmentInformation";
}
@if (Session["UserName"] != null)
{
    <html>
    <head>
        <title>Departman Bilgileri</title>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/AdminUI/DepartmentInformation">Departman Bilgileri</a>
                </div>
            </div>
        </nav>
        <table class="table table-bordered">
            <tr>
                <th>Departman Id</th>
                <th>Departman Adı</th>
                <th>Sil</th>
                <th>Güncelle</th>
            </tr>
            <tbody>
                @foreach (var information in Model)
                {
                    <tr>
                        <td>@information.DepartmentId</td>
                        <td>@information.DepartmentName</td>
                        <td><a class="btn btn-danger" href="/AdminUI/DeleteDepartment/@information.DepartmentId" id="BtnSil">Sil</a></td>
                        <td><a class="btn btn-success" href="/AdminUI/UpdateDepartment/@information.DepartmentId">Güncelle</a></td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            <form method="post">
                <div class="form-group">
                    <label>Departman Adı</label>
                    <input type="text" class="form-control" name="DepartmentName" required />
                </div>
                <div style="margin-top:15px">
                    <button class="btn btn-info" href="/AdminUI/DepartmentInformation">Ekle</button>
                </div>
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    <div style="color:red">
                        @ViewBag.Message
                    </div>
                }
            </form>
        </div>       
    </body>
</html>
}
else
{
    <a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}

TelephoneDirectory/Views/AdminUI/Index.cshtml
@using TelephoneDirectory.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Working>
@{
    ViewBag.Title = "Index";
}
@if (Session["UserName"] != null)
{
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Kullanıcı Bilgileri</a>
            </div>
        </div>
    </nav>
    <table class="table table-bordered">
        <tr>
            <th>Ad</th>
            <th>Soyad</th>
            <th>Telefon Numarası</th>
            <th>Departman</th>
            <th>Yönetici Bilgisi</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>        
        <tbody>
            @foreach (var information in Model)
            {
                <tr>
                    <td>@information.Name</td>
                    <td>@information.Surname</td>
                    <td>@information.TelephoneNumber</td>
                    <td>@information.Department1.DepartmentName</td>
                    <td>@information.Administrator1.AdministratorName</td>
                    <td><a class="btn btn-danger" href="/AdminUI/Delete/@information.WorkingId">Sil</a></td>
                    <td><a class="btn btn-success" href="/AdminUI/Update/@information.WorkingId">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
    <a class="btn btn-primary" href="/AdminUI/AdminOperation">Admin İşlemleri</a>
    <a class="btn btn-primary" href="/AdminUI/AdministratorOperation">Yönetici İşlemleri</a>
    <a class="btn btn-primary" href="/AdminUI/AddNewWorking">Yeni Çalışan Ekle</a>
    <a class="btn btn-primary" href="/AdminUI/DepartmentInformation">Departman Bilgileri</a>
    <a class="btn btn-primary" href="/AdminUI/LogOut">Çıkış Yap</a>
}
else
{
    <a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}

TelephoneDirectory/Views/AdminUI/Login.cshtml
@model TelephoneDirectory.Models.Entity.Admin
@{
    ViewBag.Title = "Login";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Yeni Kullanıcı Ekle</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    @using (Html.BeginForm("Login", "AdminUI", FormMethod.Post))
    {
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand">Admin Login</a>
                </div>
            </div>
        </nav>
        <div>
            <form>
                <div class="form-group">
                    <label>Kullanıcı Adı</label>
                    <input type="text" class="form-control" name="UserName" required />
                </div>
                <div class="form-group">
                    <label>Sifre</label>
                    <input type="password" class="form-control" name="Password" required />
                </div>
                <div style="margin-top:15px">
                    <button class="btn btn-info" href="/AdminUI/Index">Giriş</button>
                </div>
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    <div style="color:red">
                        @ViewBag.Message
                    </div>
                }

            </form>
        </div>


    }
    
</body>
</html>

TelephoneDirectory/Views/AdminUI/Update.cshtml
@model TelephoneDirectory.Models.Entity.Working
@{
    ViewBag.Title = "Update";
}
@if (Session["UserName"] != null)
{
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Kullanıcı Bilgileri Güncelle</a>
            </div>
        </div>
    </nav>
    using (Html.BeginForm("UpdateData", "AdminUI", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.WorkingId)
            @Html.TextBoxFor(m => m.WorkingId, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.Surname)
            @Html.TextBoxFor(m => m.Surname, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.TelephoneNumber)
            @Html.TextBoxFor(m => m.TelephoneNumber, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.Department1.DepartmentName)
            @Html.TextBoxFor(m => m.Department1.DepartmentName, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.Administrator)
            @Html.TextBoxFor(m => m.Administrator1.AdministratorName, new { @class = "form-control" })
            <br />
        </div>
        <div>
            <button class="btn btn-info">Güncelle</button>
        </div>
    }
}
else
{
    <a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}

TelephoneDirectory/Views/AdminUI/UpdateDepartment.cshtml
@model TelephoneDirectory.Models.Entity.Department
@{
    ViewBag.Title = "UpdateDepartment";
}
@if (Session["UserName"] != null)
{
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Departman Güncelle</a>
            </div>
        </div>
    </nav>
    using (Html.BeginForm("UpdateDataDepartment", "AdminUI", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.DepartmentId)
            @Html.TextBoxFor(m => m.DepartmentId, new { @class = "form-control" })
            <br />
            @Html.LabelFor(m => m.DepartmentName)
            @Html.TextBoxFor(m => m.DepartmentName, new { @class = "form-control" })
            <br />
        </div>
        <div>
            <button class="btn btn-info">Güncelle</button>
        </div>
    }
}
else
{
    <a class="btn btn-success" href="/AdminUI/Login">Lütfen Giriş Yapınız</a>
}